name: Update default CodeQL bundle
description: Updates 'src/defaults.json' to point to a new CodeQL bundle release.

runs:
  using: composite
  steps:
    - name: Install ts-node
      shell: bash
      run: npm install -g ts-node

    - name: Run update script
      working-directory: ${{ github.action_path }}
      shell: bash
      run: ts-node ./index.ts
